### ISSUE TITLE
Is there a plan to provide typescript binding?

### ISSUE THREAD

**Issue by Roy-Kid** [chemfiles/chemfiles#469]
I want to use chem files in js/ts. Is there any possible that use wasm-binding to bind rust chemfiles with ts?

**Comment by Luthaf** [comment]
There is a work in progress version here: https://github.com/chemfiles/chemfiles.js/. This is directly compiling C++ to WASM, and calling it from JS, not using Rust's binding to chemfiles at all. 

There are a couple of rough edges around handling files in the browser, and documentation would be very sparse, but it should be working.

**Comment by Roy-Kid** [comment]
Thanks a lot! That is what I really want. I will have a try!

**Comment by Roy-Kid** [comment]
Hi, I am so sorry to bother you. I tried every possible way to introduce chemfiles into my typescript project, but always failed. The last error is 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'stackSave')
    at stackAutoclean (stack.ts:32:31)
    at new Trajectory (trajectory.ts:64:46)
    at load_traj (load.js?16d2:6:1)
    at MolvisScene.load_traj (scene.js?c4e4:40:1)
    at eval (index.js?b635:37:1)
    at ./src/index.js (bundle.js:10133:1)
    at __webpack_require__ (bundle.js:10162:33)
    at bundle.js:11234:37
    at bundle.js:11236:12
```
Could you kindly release a very preview version of npm package so I can use it in my project?

**Comment by Luthaf** [comment]
Right, I suspected something like this might happen, I haven't touched this project for a while. I'll try to give this a go ASAP, but I'll be away from a keyboard for the next month, so it might take some time.

**Comment by Roy-Kid** [comment]
Thanks! Enjoy your vacation!
